### ISSUE TITLE
Set Up hybris B2C accelerator using HSQL db

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#1]
**As a Developer**
I want to have local hybris environment with B2C accelerator (on HSQL db),
So that I could work with hybris platform on my local machine

**AC:**
hybris installed
hybris built
hybris initialized
checkout process could be successfully done
**Tips:**
How to install -- https://wiki.hybris.com/display/tr52/Telco+Accelerator
Development environment setup example -- https://kb.epam.com/display/ECOMCC/Dev-Environment+Setup+for+iPromoTarget+project
EPAM how-to -- https://kb.epam.com/display/ECOMCC/Platform+Installation+Instructions

In case of checkout trouble, use the following link
https://wiki.hybris.com/display/accdoc50to56/b2ccheckout+AddOn

**Comment by oleksandra-holovina** [comment]
![checkout](https://user-images.githubusercontent.com/13811312/27382477-da40f660-568f-11e7-9ba6-dd6b3567afcf.png)
