### ISSUE TITLE
Generate custom accelerator extension

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#2]
**As a Developer**
I need to have custom extension to separate my features from B2C accelerator.

**AC:**

Next extension should be created and added to Hybris:
trainingorganizations

package should be com.epam.training
Tips:
https://wiki.hybris.com/display/release5/Creating+a+New+Extension

**Comment by oleksandra-holovina** [comment]
![checkout](https://user-images.githubusercontent.com/13811312/27383397-89531842-5693-11e7-8c0f-c7de6080182c.png)
