### ISSUE TITLE
Switch DB to MySQL

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#5]
**As a developer**
I need to use data-source which allows me to use row isolation level transactions, for example MySQL.

**AC:**
1. MySQL installed;
2. MySQL is used by Hybris.

Tips:
https://www.percona.com/blog/2014/01/28/10-mysql-performance-tuning-settings-after-installation/

Please check configuration **innodb_flush_log_at_trx_commit**

**Comment by oleksandra-holovina** [comment]
![mysql](https://user-images.githubusercontent.com/13811312/27433618-23a27dfa-575e-11e7-8c8e-7dab3190a3cd.png)
