### ISSUE TITLE
Add organization model

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#6]
**As a content manager**
I want Customer model (OOTB - out of the box model) to be extended with next fields:
 **graduation**.
Create new Organization model in Hybris. Add many-to-many relation between Customer and Organization models.

**AC:**
For Customer model:
graduation field: Enum type. It indicates maximum graduation which Customer has based on it's education. Calculates automatically based on Organizations of this Customer.
organisations field: is many-to-many relationship (so this is collection).

For Organisation model:
PK - primary key
name field: it contains localized values.
faculty field : String
graduation field : Enum
All these fields should be mandatory.

Technical tips:
https://wiki.hybris.com/display/release5/items.xml+Element+Reference
https://wiki.hybris.com/display/release5/Dynamic+Attributes
https://wiki.hybris.com/display/release5/How+To+Create+Dynamic+Attributes+-+Tutorial#HowToCreateDynamicAttributes-Tutorial-ImplementtheDynamicAttributeHandler
https://wiki.hybris.com/display/R5T/Trail+~+Dynamic+Model+Attributes

**Comment by oleksandra-holovina** [comment]
https://github.com/oleksandra-holovina/hybris-mentoring/commit/ec7f050c2776e3785c3dab11feea2508aa5a0429
https://github.com/oleksandra-holovina/hybris-mentoring/commit/b1bc20e7f79c0e1026e31cfc47c5fa3d4613e3bd
https://github.com/oleksandra-holovina/hybris-mentoring/commit/4122e3e0ba476a063e5fdca311a5417d3bf9387d
https://github.com/oleksandra-holovina/hybris-mentoring/commit/beb3915b60c09249885cce410819bfbaf9ad4fd5
https://github.com/oleksandra-holovina/hybris-mentoring/commit/8d1eab3da781e44b9a0ed40c8ee3c8cfab534f99
