### ISSUE TITLE
Editing Organizations in HMC

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#7]
**As a content manager**
I want Organizations node be available in hMC
So that Customer’s Organizations can be edited, created and deleted

**AC:**
HMC has a view for editing Organizations properties
User View in HMC has an attribute to assign or remove an organization

**Technical tips:**
https://wiki.hybris.com/display/tr51/Trail+~+Integration+in+the+hMC

**Comment by oleksandra-holovina** [comment]
https://github.com/oleksandra-holovina/hybris-mentoring/commit/c8b50f820bf754aa223b96ded5c589cd1b048a75
