### ISSUE TITLE
Extend Registration form

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#8]
**As a customer**
I want to be able to specify Organizations where I got my graduation.

*AC*
Registration form contains filed which allows user to specify list of organizations.
Filed is optional.

**Comment by oleksandra-holovina** [comment]
https://github.com/oleksandra-holovina/hybris-mentoring/tree/organization_dropdown/Hybris/hybris/bin/custom/training
