### ISSUE TITLE
Create media folder to give a possibility to assign images to products from this folder

### ISSUE THREAD

**Issue by ibiliaiev** [oleksandra-holovina/hybris-mentoring#9]
**As hybris admin**
I want to have a possibility to assign images to products selected from specially tuned media folder
So that I have a folder where I can place images in and use them later from hMC.

**AC**
Media folder is configured
Images from media folder could be applied to products

**Technical tips**
https://wiki.hybris.com/display/release5/Secure+Media+Access
https://wiki.hybris.com/display/tr52/Trail+~+MediaConversion

**Comment by oleksandra-holovina** [comment]
https://github.com/oleksandra-holovina/hybris-mentoring/commit/6be7dcce697389d8694c85da962f92686de8494b
